{{ $count := .Values.totalCount | int }}

{{ range $i, $e := until $count }}

{{ $counter := add $i 1}}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name}}-{{ $counter }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.pv.path }}-{{ $counter }}"

---
{{ end }}