{{ $values := $.Values }}
{{ $replicaCount := .Values.replicaCount | int }}

{{ range $i, $e := until $replicaCount }}

{{ $counter := add $i 1}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ $values.basename }}-{{ $counter }}"
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{- $values.path -}}{{- $counter -}}"

---
{{ end }}